import { NextRequest, NextResponse } from 'next/server';

// Comprehensive translations for Indian coastal languages
const manualTranslations: Record<string, Record<string, string>> = {
  // Hindi translations
  hi: {
    'CORSAIR': 'कॉर्सेयर',
    'Dashboard': 'डैशबोर्ड',
    'Live Map': 'लाइव मैप',
    'My Reports': 'मेरी रिपोर्ट्स',
    'All Reports': 'सभी रिपोर्ट्स',
    'Social Media': 'सोशल मीडिया',
    'Analytics': 'एनालिटिक्स',
    'Logout': 'लॉगआउट',
    'Welcome': 'स्वागत',
    'Report Incident': 'घटना की रिपोर्ट करें',
    'Coastal Flooding': 'तटीय बाढ़',
    'Storm Surge': 'तूफानी लहर',
    'High Tide': 'उच्च ज्वार',
    'Beach Erosion': 'समुद्र तट क्षरण',
    'Oil Spill': 'तेल रिसाव',
    'Marine Pollution': 'समुद्री प्रदूषण',
    'Infrastructure Damage': 'बुनियादी ढांचे की क्षति',
    'Wildlife Impact': 'वन्यजीव प्रभाव',
    'Critical': 'गंभीर',
    'High': 'उच्च',
    'Medium': 'मध्यम',
    'Low': 'कम',
    'Approve': 'स्वीकृत करें',
    'Reject': 'अस्वीकार करें',
    'Status': 'स्थिति',
    'Severity': 'गंभीरता',
    'Description': 'विवरण',
    'Location': 'स्थान',
    'Date': 'तारीख',
    'Sign In': 'साइन इन',
    'Sign Up': 'साइन अप',
    'Email': 'ईमेल',
    'Password': 'पासवर्ड',
    'Name': 'नाम',
    'Language': 'भाषा',
    'Select Language': 'भाषा चुनें',
    // Report form translations
    'Report an Incident': 'एक घटना की रिपोर्ट करें',
    'Fill out the form below to report a hazard. Your submission is vital for community safety.': 'खतरे की रिपोर्ट करने के लिए नीचे दिया गया फॉर्म भरें। आपका योगदान समुदायिक सुरक्षा के लिए महत्वपूर्ण है।',
    'Event Type': 'घटना का प्रकार',
    'Unusual Tides': 'असामान्य ज्वार-भाटा',
    'Flooding': 'बाढ़',
    'Coastal Damage': 'तटीय क्षति',
    'High Waves': 'ऊंची लहरें',
    'Swell Surge': 'सूजन वृद्धि',
    'Other': 'अन्य',
    'Photo Evidence': 'फोटो प्रमाण',
    'Get Current Location': 'वर्तमान स्थान प्राप्त करें',
    'Cancel': 'रद्द करें',
    'Submit Report': 'रिपोर्ट जमा करें',
    // Event type translations (with dashes and spaces)
    'coastal damage': 'तटीय क्षति',
    'unusual tides': 'असामान्य ज्वार-भाटा',
    'flooding': 'बाढ़',
    'high waves': 'ऊंची लहरें',
    'swell surge': 'सूजन वृद्धि',
    'approved reports shown.': 'अनुमोदित रिपोर्ट दिखाई गई हैं।',
    'Showing default location.': 'डिफ़ॉल्ट स्थान दिखाया जा रहा है।',
    'This may take a few seconds': 'इसमें कुछ सेकंड लग सकते हैं',
    'Locating you on the map...': 'मानचित्र पर आपका स्थान निर्धारित कर रहे हैं...',
    'Getting your location...': 'आपका स्थान प्राप्त कर रहे हैं...',
    'Real-time view of coastal hazard reports in your area': 'आपके क्षेत्र में तटीय खतरे की रिपोर्ट का वास्तविक समय दृश्य',
    'Hide Reports': 'रिपोर्ट छुपाएं',
    'Show Reports': 'रिपोर्ट दिखाएं',
    // Community Feed and Dashboard translations
    'Community Feed': 'समुदायिक फ़ीड',
    'Stay updated with latest reports and social media activity about coastal hazards in your area.': 'अपने क्षेत्र में तटीय खतरों के बारे में नवीनतम रिपोर्ट और सोशल मीडिया गतिविधि के साथ अपडेटेड रहें।',
    'Refresh': 'रीफ्रेश',
    'Citizen Reports': 'नागरिक रिपोर्ट',
    'No Reports Yet': 'अभी तक कोई रिपोर्ट नहीं',
    'Citizen reports will appear here when submitted.': 'नागरिक रिपोर्ट यहाँ दिखाई देंगी जब जमा की जाएंगी।',
    'No Social Media Activity': 'कोई सोशल मीडिया गतिविधि नहीं',
    'Social media posts about coastal hazards will appear here.': 'तटीय खतरों के बारे में सोशल मीडिया पोस्ट यहाँ दिखाई देंगी।',
    'Authentication Status': 'प्रमाणीकरण स्थिति',
    'This box checks the live Firebase Auth state and user data from Firestore.': 'यह बॉक्स लाइव Firebase Auth स्थिति और Firestore से उपयोगकर्ता डेटा की जाँच करता है।',
    'Live Auth Status:': 'लाइव प्रमाणीकरण स्थिति:',
    'Checking...': 'जाँच रहे हैं...',
    'Logged In': 'लॉग इन',
    'Not Logged In': 'लॉग इन नहीं',
    'Live User Email:': 'लाइव उपयोगकर्ता ईमेल:',
    'Name from DB:': 'डेटाबेस से नाम:',
    'Role from DB:': 'डेटाबेस से भूमिका:',
    'Loading...': 'लोड हो रहा है...',
    'citizen': 'नागरिक',
    // Analyst Dashboard translations
    'Analyst Dashboard': 'विश्लेषक डैशबोर्ड',
    'Review approved reports and issue alerts for coastal hazards.': 'तटीय खतरों के लिए अनुमोदित रिपोर्ट की समीक्षा करें और अलर्ट जारी करें।',
    'Coastal Hazard Analysis Center': 'तटीय खतरा विश्लेषण केंद्र',
    'Review approved reports, assess threats, and issue emergency alerts to coastal communities.': 'अनुमोदित रिपोर्ट की समीक्षा करें, खतरों का आकलन करें, और तटीय समुदायों को आपातकालीन अलर्ट जारी करें।',
    'No Reports Found': 'कोई रिपोर्ट नहीं मिली',
    'No approved reports with photos available yet.': 'अभी तक फोटो के साथ कोई अनुमोदित रिपोर्ट उपलब्ध नहीं है।',
    'No reports match your current filters.': 'आपके वर्तमान फिल्टर से कोई रिपोर्ट मेल नहीं खाती।',
    'Please sign in to access the analyst dashboard.': 'विश्लेषक डैशबोर्ड तक पहुंचने के लिए कृपया साइन इन करें।',
    'Issue Alert': 'अलर्ट जारी करें',
    'Alert Issued': 'अलर्ट जारी किया गया',
    'Approved:': 'अनुमोदित:',
    'Alert issued on': 'अलर्ट जारी किया गया',
    'Issue an alert to people within the specified radius of this incident.': 'इस घटना के निर्दिष्ट त्रिज्या के भीतर लोगों को अलर्ट जारी करें।',
    'Alert Type': 'अलर्ट प्रकार',
    'Warning': 'चेतावनी',
    'Advisory': 'सलाह',
    'Evacuation': 'निकासी',
    'Alert Message': 'अलर्ट संदेश',
    'Alert Radius (km)': 'अलर्ट त्रिज्या (किमी)',
    'Issuing...': 'जारी कर रहे हैं...'
  },
  // Bengali translations
  bn: {
    'CORSAIR': 'কর্সেয়ার',
    'Dashboard': 'ড্যাশবোর্ড',
    'Live Map': 'লাইভ ম্যাপ',
    'My Reports': 'আমার রিপোর্ট',
    'All Reports': 'সমস্ত রিপোর্ট',
    'Social Media': 'সোশ্যাল মিডিয়া',
    'Analytics': 'অ্যানালিটিক্স',
    'Logout': 'লগআউট',
    'Welcome': 'স্বাগতম',
    'Report Incident': 'ঘটনা রিপোর্ট করুন',
    'Coastal Flooding': 'উপকূলীয় বন্যা',
    'Storm Surge': 'ঝড়ের ঢেউ',
    'High Tide': 'উচ্চ জোয়ার',
    'Beach Erosion': 'সৈকত ক্ষয়',
    'Oil Spill': 'তেল ছড়িয়ে পড়া',
    'Marine Pollution': 'সামুদ্রিক দূষণ',
    'Infrastructure Damage': 'অবকাঠামো ক্ষতি',
    'Wildlife Impact': 'বন্যপ্রাণীর প্রভাব',
    'Critical': 'গুরুতর',
    'High': 'উচ্চ',
    'Medium': 'মধ্যম',
    'Low': 'কম',
    'Approve': 'অনুমোদন',
    'Reject': 'প্রত্যাখ্যান',
    'Status': 'অবস্থা',
    'Severity': 'তীব্রতা',
    'Description': 'বিবরণ',
    'Location': 'অবস্থান',
    'Date': 'তারিখ',
    'Sign In': 'সাইন ইন',
    'Sign Up': 'সাইন আপ',
    'Email': 'ইমেইল',
    'Password': 'পাসওয়ার্ড',
    'Name': 'নাম',
    'Language': 'ভাষা',
    'Select Language': 'ভাষা নির্বাচন করুন',
    // Report form translations
    'Report an Incident': 'একটি ঘটনা রিপোর্ট করুন',
    'Fill out the form below to report a hazard. Your submission is vital for community safety.': 'একটি বিপদ রিপোর্ট করতে নিচের ফর্মটি পূরণ করুন। আপনার জমা দেওয়া সম্প্রদায়ের নিরাপত্তার জন্য গুরুত্বপূর্ণ।',
    'Event Type': 'ইভেন্টের ধরন',
    'Unusual Tides': 'অস্বাভাবিক জোয়ার-ভাটা',
    'Flooding': 'বন্যা',
    'Coastal Damage': 'উপকূলীয় ক্ষতি',
    'High Waves': 'উঁচু ঢেউ',
    'Swell Surge': 'স্ফীতি বৃদ্ধি',
    'Other': 'অন্যান্য',
    'Photo Evidence': 'ছবির প্রমাণ',
    'Get Current Location': 'বর্তমান অবস্থান পান',
    'Cancel': 'বাতিল',
    'Submit Report': 'রিপোর্ট জমা দিন',
    // Event type variations for database values
    'coastal damage': 'উপকূলীয় ক্ষতি',
    'unusual tides': 'অস্বাভাবিক জোয়ার-ভাটা',
    'flooding': 'বন্যা',
    'high waves': 'উঁচু ঢেউ',
    'swell surge': 'স্ফীতি বৃদ্ধি',
    'other': 'অন্যান্য',
    // Community Feed and Dashboard translations
    'Community Feed': 'কমিউনিটি ফিড',
    'Stay updated with latest reports and social media activity about coastal hazards in your area.': 'আপনার এলাকার তটীয় বিপদ সম্পর্কে সর্বশেষ রিপোর্ট এবং সোশ্যাল মিডিয়া কার্যকলাপের সাথে আপডেট থাকুন।',
    'Refresh': 'রিফ্রেশ',
    'Citizen Reports': 'নাগরিক রিপোর্ট',
    'No Reports Yet': 'এখনও কোন রিপোর্ট নেই',
    'Citizen reports will appear here when submitted.': 'নাগরিক রিপোর্ট জমা দেওয়া হলে এখানে দেখা যাবে।',
    'No Social Media Activity': 'কোন সোশ্যাল মিডিয়া কার্যকলাপ নেই',
    'Social media posts about coastal hazards will appear here.': 'তটীয় বিপদ সম্পর্কে সোশ্যাল মিডিয়া পোস্ট এখানে দেখা যাবে।',
    'Authentication Status': 'প্রমাণীকরণ অবস্থা',
    'This box checks the live Firebase Auth state and user data from Firestore.': 'এই বাক্স লাইভ Firebase Auth অবস্থা এবং Firestore থেকে ব্যবহারকারীর ডেটা পরীক্ষা করে।',
    'Live Auth Status:': 'লাইভ প্রমাণীকরণ অবস্থা:',
    'Checking...': 'পরীক্ষা করা হচ্ছে...',
    'Logged In': 'লগ ইন',
    'Not Logged In': 'লগ ইন নেই',
    'Live User Email:': 'লাইভ ব্যবহারকারী ইমেইল:',
    'Name from DB:': 'ডেটাবেস থেকে নাম:',
    'Role from DB:': 'ডেটাবেস থেকে ভূমিকা:',
    'Loading...': 'লোড হচ্ছে...',
    'citizen': 'নাগরিক',
    // Analyst Dashboard translations
    'Analyst Dashboard': 'বিশ্লেষক ড্যাশবোর্ড',
    'Review approved reports and issue alerts for coastal hazards.': 'উপকূলীয় বিপদের জন্য অনুমোদিত রিপোর্ট পর্যালোচনা করুন এবং সতর্কতা জারি করুন।',
    'Coastal Hazard Analysis Center': 'উপকূলীয় বিপদ বিশ্লেষণ কেন্দ্র',
    'Review approved reports, assess threats, and issue emergency alerts to coastal communities.': 'অনুমোদিত রিপোর্ট পর্যালোচনা করুন, হুমকি মূল্যায়ন করুন, এবং উপকূলীয় সম্প্রদায়গুলিকে জরুরি সতর্কতা জারি করুন।',
    'No Reports Found': 'কোন রিপোর্ট পাওয়া যায়নি',
    'No approved reports with photos available yet.': 'এখনও ছবি সহ কোন অনুমোদিত রিপোর্ট উপলব্ধ নেই।',
    'No reports match your current filters.': 'আপনার বর্তমান ফিল্টারের সাথে কোন রিপোর্ট মেলে না।',
    'Please sign in to access the analyst dashboard.': 'বিশ্লেষক ড্যাশবোর্ড অ্যাক্সেস করতে দয়া করে সাইন ইন করুন।',
    'Issue Alert': 'সতর্কতা জারি করুন',
    'Alert Issued': 'সতর্কতা জারি করা হয়েছে',
    'Approved:': 'অনুমোদিত:',
    'Alert issued on': 'সতর্কতা জারি করা হয়েছে',
    'Issue an alert to people within the specified radius of this incident.': 'এই ঘটনার নির্দিষ্ট ব্যাসার্ধের মধ্যে মানুষদের একটি সতর্কতা জারি করুন।',
    'Alert Type': 'সতর্কতার ধরন',
    'Warning': 'সতর্কতা',
    'Advisory': 'পরামর্শ',
    'Evacuation': 'সরিয়ে নেওয়া',
    'Alert Message': 'সতর্কতা বার্তা',
    'Alert Radius (km)': 'সতর্কতা ব্যাসার্ধ (কিমি)',
    'Issuing...': 'জারি করা হচ্ছে...'
  },
  // Tamil translations
  ta: {
    'CORSAIR': 'கார்சேர்',
    'Dashboard': 'டாஷ்போர்டு',
    'Live Map': 'நேரடி வரைபடம்',
    'My Reports': 'எனது அறிக்கைகள்',
    'All Reports': 'அனைத்து அறிக்கைகள்',
    'Social Media': 'சமூக ஊடகம்',
    'Analytics': 'பகுப்பாய்வு',
    'Logout': 'வெளியேறு',
    'Welcome': 'வரவேற்கிறோம்',
    'Report Incident': 'சம்பவத்தை அறிக்கையிடுங்கள்',
    'Coastal Flooding': 'கடலோர வெள்ளம்',
    'Storm Surge': 'புயல் அலை',
    'High Tide': 'உயர் அலை',
    'Beach Erosion': 'கடற்கரை அரிப்பு',
    'Oil Spill': 'எண்ணெய் கசிவு',
    'Marine Pollution': 'கடல் மாசுபாடு',
    'Infrastructure Damage': 'உள்கட்டமைப்பு சேதம்',
    'Wildlife Impact': 'வனவிலங்கு தாக்கம்',
    'Critical': 'முக்கியமான',
    'High': 'உயர்ந்த',
    'Medium': 'நடுத்தர',
    'Low': 'குறைந்த',
    'Approve': 'அங்கீகரிக்க',
    'Reject': 'நிராகரிக்க',
    'Status': 'நிலை',
    'Severity': 'தீவிரம்',
    'Description': 'விளக்கம்',
    'Location': 'இடம்',
    'Date': 'தேதி',
    'Sign In': 'உள்நுழை',
    'Sign Up': 'பதிவு செய்',
    'Email': 'மின்னஞ்சல்',
    'Password': 'கடவுச்சொல்',
    'Name': 'பெயர்',
    'Language': 'மொழி',
    'Select Language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
    // Report form translations
    'Report an Incident': 'ஒரு சம்பவத்தை அறிவிக்கவும்',
    'Fill out the form below to report a hazard. Your submission is vital for community safety.': 'ஆபத்தை அறிவிக்க கீழே உள்ள படிவத்தை பூர்த்தி செய்யுங்கள். உங்கள் சமர்ப்பணம் சமுதாய பாதுகாப்பிற்கு முக்கியமானது.',
    'Event Type': 'நிகழ்வு வகை',
    'Unusual Tides': 'அசாதாரண அலைகள்',
    'Flooding': 'வெள்ளம்',
    'Coastal Damage': 'கடலோர சேதம்',
    'High Waves': 'உயர் அலைகள்',
    'Swell Surge': 'வீக்க எழுச்சி',
    'Other': 'மற்றவை',
    'Photo Evidence': 'புகைப்பட ஆதாரம்',
    'Get Current Location': 'தற்போதைய இடத்தைப் பெறுங்கள்',
    'Cancel': 'ரத்து செய்',
    'Submit Report': 'அறிக்கையை சமர்ப்பிக்கவும்',
    // Event type variations for database values
    'coastal damage': 'கடலோர சேதம்',
    'unusual tides': 'அசாதாரண அலைகள்',
    'flooding': 'வெள்ளம்',
    'high waves': 'உயர் அலைகள்',
    'swell surge': 'வீக்க எழுச்சி',
    'other': 'மற்றவை',
    // Community Feed and Dashboard translations
    'Community Feed': 'சமுதாய ஊட்டம்',
    'Stay updated with latest reports and social media activity about coastal hazards in your area.': 'உங்கள் பகுதியில் கடலோர ஆபத்துகள் பற்றிய சமீபத்திய அறிக்கைகள் மற்றும் சமூக ஊடக செயல்பாடுகளுடன் புதுப்பித்த நிலையில் இருங்கள்।',
    'Refresh': 'புதுப்பிக்கவும்',
    'Citizen Reports': 'குடிமக்கள் அறிக்கைகள்',
    'No Reports Yet': 'இன்னும் அறிக்கைகள் இல்லை',
    'Citizen reports will appear here when submitted.': 'குடிமக்கள் அறிக்கைகள் சமர்ப்பிக்கப்படும்போது இங்கே தோன்றும்।',
    'No Social Media Activity': 'சமூக ஊடக செயல்பாடு இல்லை',
    'Social media posts about coastal hazards will appear here.': 'கடலோர ஆபத்துகள் பற்றிய சமூக ஊடக இடுகைகள் இங்கே தோன்றும்।',
    'Authentication Status': 'அங்கீகார நிலை',
    'This box checks the live Firebase Auth state and user data from Firestore.': 'இந்த பெட்டி நேரடி Firebase அங்கீகார நிலை மற்றும் Firestore இலிருந்து பயனர் தரவை சரிபார்க்கிறது।',
    'Live Auth Status:': 'நேரடி அங்கீகார நிலை:',
    'Checking...': 'சரிபார்க்கிறது...',
    'Logged In': 'உள்நுழைந்துள்ளது',
    'Not Logged In': 'உள்நுழையவில்லை',
    'Live User Email:': 'நேரடி பயனர் மின்னஞ்சல்:',
    'Name from DB:': 'தரவுத்தளத்திலிருந்து பெயர்:',
    'Role from DB:': 'தரவுத்தளத்திலிருந்து பங்கு:',
    'Loading...': 'ஏற்றுகிறது...',
    'citizen': 'குடிமகன்',
    // Analyst Dashboard translations
    'Analyst Dashboard': 'பகுப்பாய்வாளர் டாஷ்போர்டு',
    'Review approved reports and issue alerts for coastal hazards.': 'கடலோர ஆபத்துகளுக்கான அங்கீகரிக்கப்பட்ட அறிக்கைகளை மதிப்பாய்வு செய்து எச்சரிக்கைகளை வெளியிடுங்கள்.',
    'Coastal Hazard Analysis Center': 'கடலோர ஆபத்து பகுப்பாய்வு மையம்',
    'Review approved reports, assess threats, and issue emergency alerts to coastal communities.': 'அங்கீகரிக்கப்பட்ட அறிக்கைகளை மதிப்பாய்வு செய்து, அச்சுறுத்தல்களை மதிப்பீடு செய்து, கடலோர சமுதாயங்களுக்கு அவசர எச்சரிக்கைகளை வெளியிடுங்கள்.',
    'No Reports Found': 'அறிக்கைகள் எதுவும் இல்லை',
    'No approved reports with photos available yet.': 'புகைப்படங்களுடன் அங்கீகரிக்கப்பட்ட அறிக்கைகள் இன்னும் கிடைக்கவில்லை.',
    'No reports match your current filters.': 'உங்கள் தற்போதைய வடிப்பான்களுக்கு எந்த அறிக்கையும் பொருந்தவில்லை.',
    'Please sign in to access the analyst dashboard.': 'பகுப்பாய்வாளர் டாஷ்போர்டை அணுக தயவுசெய்து உள்நுழையுங்கள்.',
    'Issue Alert': 'எச்சரிக்கை வெளியிடுங்கள்',
    'Alert Issued': 'எச்சரிக்கை வெளியிடப்பட்டது',
    'Approved:': 'அங்கீகரிக்கப்பட்டது:',
    'Alert issued on': 'எச்சரிக்கை வெளியிடப்பட்டது',
    'Issue an alert to people within the specified radius of this incident.': 'இந்த சம்பவத்தின் குறிப்பிட்ட ஆரத்தில் உள்ள மக்களுக்கு ஒரு எச்சரிக்கையை வெளியிடுங்கள்.',
    'Alert Type': 'எச்சரிக்கை வகை',
    'Warning': 'எச்சரிக்கை',
    'Advisory': 'ஆலோசனை',
    'Evacuation': 'வெளியேற்றம்',
    'Alert Message': 'எச்சரிக்கை செய்தி',
    'Alert Radius (km)': 'எச்சரிக்கை ஆரம் (கிமீ)',
    'Issuing...': 'வெளியிடுகிறது...'
  },
  // Telugu translations
  te: {
    'CORSAIR': 'కార్సేర్',
    'Dashboard': 'డాష్‌బోర్డ్',
    'Live Map': 'ప్రత్యక్ష మ్యాప్',
    'My Reports': 'నా నివేదికలు',
    'All Reports': 'అన్ని నివేదికలు',
    'Social Media': 'సామాజిక మాధ్యమాలు',
    'Analytics': 'విశ్లేషణలు',
    'Logout': 'లాగౌట్',
    'Welcome': 'స్వాగతం',
    'Report Incident': 'సంఘటనను నివేదించండి',
    'Coastal Flooding': 'తీర ప్రాంత వరదలు',
    'Storm Surge': 'తుఫాను అలలు',
    'High Tide': 'అధిక అలలు',
    'Beach Erosion': 'బీచ్ కోత',
    'Oil Spill': 'చమురు చలనం',
    'Marine Pollution': 'సముద్ర కాలుష్యం',
    'Infrastructure Damage': 'మౌలిక సదుపాయాల నష్టం',
    'Wildlife Impact': 'వన్యప్రాణుల ప్రభావం',
    'Critical': 'క్లిష్టమైన',
    'High': 'అధిక',
    'Medium': 'మధ్యస్థ',
    'Low': 'తక్కువ',
    'Approve': 'ఆమోదించండి',
    'Reject': 'తిరస్కరించండి',
    'Status': 'స్థితి',
    'Severity': 'తీవ్రత',
    'Description': 'వివరణ',
    'Location': 'స్థానం',
    'Date': 'తేదీ',
    'Sign In': 'సైన్ ఇన్',
    'Sign Up': 'సైన్ అప్',
    'Email': 'ఇమెయిల్',
    'Password': 'పాస్‌వర్డ్',
    'Name': 'పేరు',
    'Language': 'భాష',
    'Select Language': 'భాషను ఎంచుకోండి',
    // Report form translations
    'Report an Incident': 'ఒక సంఘటనను నివేదించండి',
    'Fill out the form below to report a hazard. Your submission is vital for community safety.': 'ప్రమాదాన్ని నివేదించడానికి దిగువ ఫారమ్‌ను పూరించండి. మీ సమర్పణ సమాజ భద్రతకు కీలకం.',
    'Event Type': 'ఈవెంట్ రకం',
    'Unusual Tides': 'అసాధారణ ఆటుపోట్లు',
    'Flooding': 'వరదలు',
    'Coastal Damage': 'తీరప్రాంత నష్టం',
    'High Waves': 'ఎత్తైన తరంగాలు',
    'Swell Surge': 'వాపు ఉప్పెన',
    'Other': 'ఇతర',
    'Photo Evidence': 'ఫోటో సాక్ష్యం',
    'Get Current Location': 'ప్రస్తుత స్థానాన్ని పొందండి',
    'Cancel': 'రద్దు చేయండి',
    'Submit Report': 'నివేదికను సమర్పించండి'
  },
  // Malayalam translations
  ml: {
    'CORSAIR': 'കോർസെയർ',
    'Dashboard': 'ഡാഷ്ബോർഡ്',
    'Live Map': 'ലൈവ് മാപ്പ്',
    'My Reports': 'എന്റെ റിപ്പോർട്ടുകൾ',
    'All Reports': 'എല്ലാ റിപ്പോർട്ടുകളും',
    'Social Media': 'സോഷ്യൽ മീഡിയ',
    'Analytics': 'അനലിറ്റിക്സ്',
    'Logout': 'ലോഗൗട്ട്',
    'Welcome': 'സ്വാഗതം',
    'Report Incident': 'സംഭവം റിപ്പോർട്ട് ചെയ്യുക',
    'Coastal Flooding': 'തീരദേശ വെള്ളപ്പൊക്കം',
    'Storm Surge': 'കൊടുങ്കാറ്റ് തിരമാല',
    'High Tide': 'ഉയർന്ന വേലിയേറ്റം',
    'Beach Erosion': 'ബീച്ച് മണ്ണൊലിപ്പ്',
    'Oil Spill': 'എണ്ണ ചോർച്ച',
    'Marine Pollution': 'സമുദ്ര മലിനീകരണം',
    'Infrastructure Damage': 'അടിസ്ഥാന സൗകര്യ നാശം',
    'Wildlife Impact': 'വന്യജീവി ആഘാതം',
    'Critical': 'നിർണായകം',
    'High': 'ഉയർന്ന',
    'Medium': 'ഇടത്തരം',
    'Low': 'കുറഞ്ഞ',
    'Approve': 'അംഗീകരിക്കുക',
    'Reject': 'നിരസിക്കുക',
    'Status': 'നില',
    'Severity': 'തീവ്രത',
    'Description': 'വിവരണം',
    'Location': 'സ്ഥാനം',
    'Date': 'തീയതി',
    'Sign In': 'സൈൻ ഇൻ',
    'Sign Up': 'സൈൻ അപ്പ്',
    'Email': 'ഇമെയിൽ',
    'Password': 'പാസ്‌വേഡ്',
    'Name': 'പേര്',
    'Language': 'ഭാഷ',
    'Select Language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    // Report form translations
    'Report an Incident': 'ഒരു സംഭവം റിപ്പോർട്ട് ചെയ്യുക',
    'Fill out the form below to report a hazard. Your submission is vital for community safety.': 'ഒരു അപകടം റിപ്പോർട്ട് ചെയ്യാൻ താഴെയുള്ള ഫോം പൂരിപ്പിക്കുക. നിങ്ങളുടെ സമർപ്പണം കമ്മ്യൂണിറ്റി സുരക്ഷയ്ക്ക് അത്യന്താപേക്ഷിതമാണ്.',
    'Event Type': 'ഇവന്റ് തരം',
    'Unusual Tides': 'അസാധാരണ വേലിയേറ്റങ്ങൾ',
    'Flooding': 'വെള്ളപ്പൊക്കം',
    'Coastal Damage': 'തീരദേശ നാശം',
    'High Waves': 'ഉയർന്ന തിരമാലകൾ',
    'Swell Surge': 'വീർപ്പുമുട്ടൽ കുതിച്ചുചാട്ടം',
    'Other': 'മറ്റുള്ളവ',
    'Photo Evidence': 'ഫോട്ടോ തെളിവ്',
    'Get Current Location': 'നിലവിലെ ലൊക്കേഷൻ നേടുക',
    'Cancel': 'റദ്ദാക്കുക',
    'Submit Report': 'റിപ്പോർട്ട് സമർപ്പിക്കുക'
  },
  // Kannada translations
  kn: {
    'CORSAIR': 'ಕಾರ್ಸೇರ್',
    'Dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'Live Map': 'ಲೈವ್ ಮ್ಯಾಪ್',
    'My Reports': 'ನನ್ನ ವರದಿಗಳು',
    'All Reports': 'ಎಲ್ಲಾ ವರದಿಗಳು',
    'Social Media': 'ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ',
    'Analytics': 'ವಿಶ್ಲೇಷಣೆ',
    'Logout': 'ಲಾಗೌಟ್',
    'Welcome': 'ಸ್ವಾಗತ',
    'Report Incident': 'ಘಟನೆಯನ್ನು ವರದಿ ಮಾಡಿ',
    'Coastal Flooding': 'ಕರಾವಳಿ ಪ್ರವಾಹ',
    'Storm Surge': 'ಚಂಡಮಾರುತದ ಅಲೆ',
    'High Tide': 'ಹೆಚ್ಚಿನ ಉಬ್ಬರ',
    'Beach Erosion': 'ಬೀಚ್ ಸವೆತ',
    'Oil Spill': 'ತೈಲ ಸೋರಿಕೆ',
    'Marine Pollution': 'ಸಾಗರ ಮಾಲಿನ್ಯ',
    'Infrastructure Damage': 'ಮೂಲಸೌಕರ್ಯ ಹಾನಿ',
    'Wildlife Impact': 'ವನ್ಯಜೀವಿ ಪ್ರಭಾವ',
    'Critical': 'ನಿರ್ಣಾಯಕ',
    'High': 'ಹೆಚ್ಚಿನ',
    'Medium': 'ಮಧ್ಯಮ',
    'Low': 'ಕಡಿಮೆ',
    'Approve': 'ಅನುಮೋದಿಸಿ',
    'Reject': 'ತಿರಸ್ಕರಿಸಿ',
    'Status': 'ಸ್ಥಿತಿ',
    'Severity': 'ತೀವ್ರತೆ',
    'Description': 'ವಿವರಣೆ',
    'Location': 'ಸ್ಥಳ',
    'Date': 'ದಿನಾಂಕ',
    'Sign In': 'ಸೈನ್ ಇನ್',
    'Sign Up': 'ಸೈನ್ ಅಪ್',
    'Email': 'ಇಮೇಲ್',
    'Password': 'ಪಾಸ್‌ವರ್ಡ್',
    'Name': 'ಹೆಸರು',
    'Language': 'ಭಾಷೆ',
    'Select Language': 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ'
  },
  // Gujarati translations
  gu: {
    'CORSAIR': 'કોર્સેર',
    'Dashboard': 'ડેશબોર્ડ',
    'Live Map': 'લાઇવ મેપ',
    'My Reports': 'મારા રિપોર્ટ્સ',
    'All Reports': 'બધા રિપોર્ટ્સ',
    'Social Media': 'સોશિયલ મીડિયા',
    'Analytics': 'વિશ્લેષણ',
    'Logout': 'લોગઆઉટ',
    'Welcome': 'સ્વાગત',
    'Report Incident': 'ઘટનાની જાણ કરો',
    'Coastal Flooding': 'દરિયાકાંઠાનું પૂર',
    'Storm Surge': 'તોફાનનો મોજો',
    'High Tide': 'મોટો ભરતી',
    'Beach Erosion': 'દરિયાકિનારાનું ધોવાણ',
    'Oil Spill': 'તેલનો ફેલાવો',
    'Marine Pollution': 'દરિયાઈ પ્રદૂષણ',
    'Infrastructure Damage': 'ઇન્ફ્રાસ્ટ્રક્ચર નુકસાન',
    'Wildlife Impact': 'વન્યજીવ અસર',
    'Critical': 'ગંભીર',
    'High': 'ઊંચું',
    'Medium': 'મધ્યમ',
    'Low': 'નીચું',
    'Approve': 'મંજૂર કરો',
    'Reject': 'નકારો',
    'Status': 'સ્થિતિ',
    'Severity': 'ગંભીરતા',
    'Description': 'વર્ણન',
    'Location': 'સ્થાન',
    'Date': 'તારીખ',
    'Sign In': 'સાઇન ઇન',
    'Sign Up': 'સાઇન અપ',
    'Email': 'ઇમેઇલ',
    'Password': 'પાસવર્ડ',
    'Name': 'નામ',
    'Language': 'ભાષા',
    'Select Language': 'ભાષા પસંદ કરો',
    // Report form translations
    'Report an Incident': 'એક ઘટનાની જાણ કરો',
    'Event Type': 'ઇવેન્ટનો પ્રકાર',
    'Unusual Tides': 'અસામાન્ય ભરતી',
    'Flooding': 'પૂર',
    'Coastal Damage': 'દરિયાકાંઠાના નુકસાન',
    'High Waves': 'ઊંચા મોજા',
    'Other': 'અન્ય',
    'Photo Evidence': 'ફોટો પુરાવા',
    'Get Current Location': 'વર્તમાન સ્થાન મેળવો',
    'Cancel': 'રદ કરો',
    'Submit Report': 'અહેવાલ સબમિટ કરો'
  },
  // Marathi translations
  mr: {
    'CORSAIR': 'कॉर्सेअर',
    'Dashboard': 'डॅशबोर्ड',
    'Live Map': 'लाइव्ह मॅप',
    'My Reports': 'माझे अहवाल',
    'All Reports': 'सर्व अहवाल',
    'Social Media': 'सोशल मीडिया',
    'Analytics': 'विश्लेषण',
    'Logout': 'लॉगआउट',
    'Welcome': 'स्वागत',
    'Report Incident': 'घटनेचा अहवाल द्या',
    'Coastal Flooding': 'किनारपट्टीवरील पूर',
    'Storm Surge': 'वादळी लाटा',
    'High Tide': 'भरती',
    'Beach Erosion': 'समुद्रकिनारा धूप',
    'Oil Spill': 'तेल गळती',
    'Marine Pollution': 'सागरी प्रदूषण',
    'Infrastructure Damage': 'पायाभूत सुविधांचे नुकसान',
    'Wildlife Impact': 'वन्यजीव प्रभाव',
    'Critical': 'गंभीर',
    'High': 'उच्च',
    'Medium': 'मध्यम',
    'Low': 'कमी',
    'Approve': 'मंजूर करा',
    'Reject': 'नाकारा',
    'Status': 'स्थिती',
    'Severity': 'गंभीरता',
    'Description': 'वर्णन',
    'Location': 'स्थान',
    'Date': 'दिनांक',
    'Sign In': 'साइन इन',
    'Sign Up': 'साइन अप',
    'Email': 'ईमेल',
    'Password': 'पासवर्ड',
    'Name': 'नाव',
    'Language': 'भाषा',
    'Select Language': 'भाषा निवडा'
  }
};

export async function POST(request: NextRequest) {
  try {
    const { text, targetLanguage } = await request.json();

    if (!text || !targetLanguage) {
      return NextResponse.json(
        { error: 'Text and target language are required' },
        { status: 400 }
      );
    }

    // Return original text if English
    if (targetLanguage === 'en') {
      return NextResponse.json({ translatedText: text });
    }

    // Check if we have a manual translation
    const languageTranslations = manualTranslations[targetLanguage];
    if (languageTranslations && languageTranslations[text]) {
      return NextResponse.json({ 
        translatedText: languageTranslations[text] 
      });
    }

    // For dynamic content or unsupported languages, try Google Translate API
    try {
      // Define supported Google Translate language codes
      const supportedLanguages = ['hi', 'bn', 'ta', 'te', 'ml', 'kn', 'gu', 'mr', 'en'];
      
      // If language is not supported, fallback to English
      const translationLanguage = supportedLanguages.includes(targetLanguage) ? targetLanguage : 'en';
      
      if (translationLanguage === 'en') {
        // Return original text for English or unsupported languages
        return NextResponse.json({ 
          translatedText: text 
        });
      }
      
      const { translate } = await import('google-translate-api-x');
      const result = await translate(text, { to: translationLanguage });
      
      // Handle different response formats
      let translatedText = text;
      if (typeof result === 'object' && result !== null) {
        if ('text' in result) {
          translatedText = result.text as string;
        } else if (Array.isArray(result) && result.length > 0 && 'text' in result[0]) {
          translatedText = result[0].text as string;
        }
      }
      
      return NextResponse.json({ 
        translatedText: translatedText 
      });
    } catch (translateError) {
      console.error('Google Translate error:', translateError);
      
      // Fallback: return original text
      return NextResponse.json({ 
        translatedText: text 
      });
    }

  } catch (error) {
    console.error('Translation API error:', error);
    return NextResponse.json(
      { error: 'Translation failed' },
      { status: 500 }
    );
  }
}
